/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ErrorImport } from './routes/error'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardWorkspaceIdImport } from './routes/dashboard/$workspaceId'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthResetpasswordImport } from './routes/auth/resetpassword'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthForgetPasswordImport } from './routes/auth/ForgetPassword'
import { Route as StudioFormIdIndexImport } from './routes/studio/$formId/index'
import { Route as StudioFormIdEditImport } from './routes/studio/$formId/edit'

// Create/Update Routes

const ErrorRoute = ErrorImport.update({
  path: '/error',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardWorkspaceIdRoute = DashboardWorkspaceIdImport.update({
  path: '/dashboard/$workspaceId',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetpasswordRoute = AuthResetpasswordImport.update({
  path: '/auth/resetpassword',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgetPasswordRoute = AuthForgetPasswordImport.update({
  path: '/auth/ForgetPassword',
  getParentRoute: () => rootRoute,
} as any)

const StudioFormIdIndexRoute = StudioFormIdIndexImport.update({
  path: '/studio/$formId/',
  getParentRoute: () => rootRoute,
} as any)

const StudioFormIdEditRoute = StudioFormIdEditImport.update({
  path: '/studio/$formId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/error': {
      preLoaderRoute: typeof ErrorImport
      parentRoute: typeof rootRoute
    }
    '/auth/ForgetPassword': {
      preLoaderRoute: typeof AuthForgetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/resetpassword': {
      preLoaderRoute: typeof AuthResetpasswordImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/$workspaceId': {
      preLoaderRoute: typeof DashboardWorkspaceIdImport
      parentRoute: typeof rootRoute
    }
    '/studio/$formId/edit': {
      preLoaderRoute: typeof StudioFormIdEditImport
      parentRoute: typeof rootRoute
    }
    '/studio/$formId/': {
      preLoaderRoute: typeof StudioFormIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ErrorRoute,
  AuthForgetPasswordRoute,
  AuthLoginRoute,
  AuthResetpasswordRoute,
  AuthSignupRoute,
  DashboardWorkspaceIdRoute,
  StudioFormIdEditRoute,
  StudioFormIdIndexRoute,
])

/* prettier-ignore-end */
